version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERR: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:11-alpine'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
volumes:
  pgdata:
